### ISSUE TITLE
`yarn test` fails with ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by pete-the-pete** [gabrielcsapo/ponticus#1]
![Screen Shot 2022-11-06 at 2 10 00 PM](https://user-images.githubusercontent.com/345985/200197849-61319ef2-7f08-4b35-b2e1-aa3400aeeb48.png)

**Comment by pete-the-pete** [comment]
A bunch of things fail/happen, but that is the first one.

**Comment by gabrielcsapo** [comment]
I have a fix locally, will push that up tonight

**Comment by pete-the-pete** [comment]
🙇
